.Preface

In order to achieve consensus on the modeling indoor spaces and their neighborhood relationships to support indoor location-based services, a UML Conceptual Model, IndoorGML 2.0 Part 1, was approved as an OGC Standard (<<ogc22-045r5>>) in June, 2025.
This model covers geometric and semantic properties of indoor spaces relevant for indoor navigation.
This IndoorGML 2.0 Part 2a: XML Encoding Standard defines how those concepts should be realized using XML schema format.
The XML encoding is intended for software developers, data providers, standards implementers, and service providers who need a structured, standard, and machine-readable representation of IndoorGML datasets using XML/GML.

[abstract]
== Abstract

The IndoorGML 2.0 Part 2a – XML Encoding Standard presents the implementation-dependent Geography Markup Language (GML) XML schema encoding of the concepts defined by the IndoorGML 2.0 Part 1 – Conceptual Model Standard (<<ogc22-045r5>>).
The XML Encoding is compliant with GML version 3.2.1 as specified by <<ogc07-036>>.
The XML encoding of IndoorGML 2.0 defines a concrete implementation schema for representing indoor spatial information, including primal space, dual space, thematic layers, interlayer connections, and navigation-related indoor features.
This encoding can be used to store and exchange 2D and/or 3D indoor space and indoor navigation network models in XML format as data sets or via web services.

This Part 2a of the Standard defines how the concepts developed in Part 1 are realized using XML Schema definitions.
The XML encoding represents a full mapping of the Conceptual Model and is derived from the UML model following the UML-to-GML/XML encoding rules.
Table 1 maps requirements classes from the IndoorGML 2.0 Conceptual Model into the implementation details documented in this standard.

.Requirements classes mapping
|===
|Conceptual Model       |Section            |XML Schema

|IndoorGML Core         |<<section-indoorxml-core>>
|<<annex_indoorxml_core_schema>>
|Navigation Extension   |<<section-indoorxml-navi>>
|<<annex_indoorxml_navi_schema>>
|===

[.preface]
== Security Considerations

No security considerations have been made for this Standard.

[.preface]
== Submitters
All questions regarding this submission should be directed to the editor or the submitters:

|===
|Name |Affiliation |Email |OGC member

|Abdoulaye Diakité |CityGeometrix Pty Ltd |abdou@citygeometrix.com |Yes
|Taehoon Kim |National Institute of Advanced Industrial Science and Technology |kim.taehoon@aist.go.jp |Yes
|Sisi Zlatanova |University of New South Wales |s.zlatanova@unsw.edu.au |Yes
|Ki-Joune Li |Pusan National University |lik@pnu.edu |Yes
|Zhiyong Wang |SpatialAlgebra Technology Limited |zhiyongwang@spatialalgebra.tech |Yes
|===


//[.preface]
//== Participants in development
//
//The following individuals participated in the development of this standard:
//- Sisi Zlatanova (University of New South Wales)
//- Abdoulaye Diakité (CityGeometrix)
//- Taehoon Kim (AIST)
//- Ki-Joune Li (Pusan National University)
//- Zhiyong Wang (SpatialAlgebra)
//