
[heading=conformance]
== Conformance

This standard defines implementation specification which specifies how the IndoorGML 2.0 Conceptual Model should be implemented using Extensible Markup Language (XML) and GML 3.2.1.
The Standardization Target for this standard is:

* Implementations of the IndoorGML 2.0 Conceptual Model using XML encodings.

Conformance with this standard shall be checked using all the relevant tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

In order to conform to this OGC® interface standard, a software implementation shall choose to implement:

* Any one of the conformance levels specified in Annex A (normative).

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.

.Conformance classes
|===
|Conformance class      |URI

|IndoorGML Core         |http://www.opengis.net/spec/indoorgml-2/2.0/xml/conf/core
|Navigation Extension   |http://www.opengis.net/spec/indoorgml-2/2.0/xml/conf/navi
|===
