= Standard template in Metanorma

The base template was taken from the GitHub project below:

* https://github.com/metanorma/mn-templates-ogc

The OGC IndoorGML 2.0 build results can be shown as below links:

* https://htmlpreview.github.io/?https://github.com/opengeospatial/IndoorGML-SWG/blob/master/IndoorGML2/IndoorGML2_metanorma/Part%20I/document.html[OGC_22-045.html]
* https://github.com/opengeospatial/IndoorGML-SWG/blob/master/IndoorGML2/IndoorGML2_metanorma/Part%20I/document.pdf[OGC_22-045.pdf]

== Content

This repository contains the content for an OGC standard.

* `document.adoc` - the main standard document with references to all sections
* remaining ``adoc``s - each section of the standard document is in a separate document: follow directions in each document to populate
* `figures` - figures go here
* `images` - Image files for graphics go here. Image files for figures go in the `figures` directory. Only place in here images not used in figures (e.g., as parts of tables, as logos, etc.)
* `requirements` - directory for requirements and requirement classes to be referenced in `clause_7_normative_text.adoc`
* `code` - sample code to accompany the standard, if desired
* `abstract_tests` - the Abstract Test Suite comprising one test for every requirement, optional
* `UML` - UML diagrams, if applicable

== Authoring (in your local system)
Documentation follows Asciidoc's syntax by default.

* See https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc Language Documentation]

Several authoring tools are available, but we recommend Visual Studio Code and AsciiDoc's extensions, which are free to use.

* https://code.visualstudio.com/[Visual Studio Code]
* https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[AsciiDoc VS Code Extension]

Finally, the special syntax and variables used in Metanorma can be found in the authoring guide at the following link.

* https://www.metanorma.org/author/ogc/[OGC document with Metanorma]


== Building (in your local system)

. (If you haven't installed Docker) Install the https://www.docker.com/products/docker-desktop/[Docker Desktop].

. Pull the Metanorma Docker container (ref: https://www.metanorma.org/install/docker/).
+
```
docker pull metanorma/metanorma
```

. Building Document
+
```
git clone https://github.com/opengeospatial/IndoorGML-SWG.git

cd IndoorGML2/IndoorGML2_metanorma/Part\ I

docker run -v "$(pwd)":/metanorma -v ${HOME}/.fontist/fonts/:/config/fonts  metanorma/metanorma metanorma compile --agree-to-terms -t ogc -x html,pdf document.adoc
```