
== Terms and Definitions

[conceptual model]
=== conceptual model

model that defines concepts of a universe of discourse

[.source]
<<iso19101-1>>

=== conceptual schema

formal description of a <<conceptual model,conceptual model>>

[.source]
<<iso19101-1>>

=== data type

set of values that lack identity

NOTE: A data type is a class with no operations whose primary purpose is to hold information.
In the IndoorGML 2.0 Conceptual Model, data types are denoted by the stereotype «DataType».

NOTE: In this SQL encoding, non-geometric UML DataTypes are encoded as PostgreSQL composite types, and geometry DataTypes are flattened onto owning feature tables as PostGIS `geometry` columns (see <<section-conventions>>).

[.source]
<<iso19103>>

=== feature

abstraction of real world phenomena

NOTE: Features are objects that have an identity that allows for distinguishing features from each other. Features can have spatial and non-spatial properties that describe the features in more detail. Spatial properties are properties that have a geometry from <<iso19107>> as data type.

NOTE: Features are denoted by the stereotype «FeatureType» in the IndoorGML 2.0 Conceptual Model.

[.source]
<<iso19101-1>>

=== relational table

persistent data structure in a relational database that stores records of a single feature type or association

NOTE: In the SQL encoding of IndoorGML 2.0, each IndoorGML 2.0 feature class is mapped to one or more relational tables.
