[[section-indoorsql-core]]
== SQL Encoding of the Core Module

[requirements_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/indoorgml-2/2.0/sql/req/core
subject:: Implementation Specification
inherit:: http://www.opengis.net/spec/indoorgml/2.0/req
requirement:: /req/core/indoorsql
requirement:: /req/core/indoorfeature
requirement:: /req/core/thematiclayer
requirement:: /req/core/primalspacelayer
requirement:: /req/core/cellspace
requirement:: /req/core/cellboundary
requirement:: /req/core/dualspacelayer
requirement:: /req/core/node
requirement:: /req/core/edge
requirement:: /req/core/interlayerconnection
====

Each feature table of the SQL encoding represents one feature class of the IndoorGML 2.0 conceptual model.

Every feature table:

* *must* have a primary key column storing a string identifier that serves as a unique identifier for the feature and can be used to represent cross-references between objects in the SQL encoding.

[[req-indoorsql]]
[requirement]
.Requirement for SQL encoding feature tables
====
[%metadata]
identifier:: /req/core/indoorsql
part:: Each feature table of the SQL encoding SHALL contain a string primary key column for the feature identifier.
====

Core code list `ENUM` types used by the core module tables are specified in <<annex_core_enums>>.

[[section-indoorfeatures]]
=== IndoorFeatures

The `IndoorFeatures` table stores instances of https://docs.ogc.org/is/22-045r5/22-045r5.html#section-indoorgml-core[IndoorFeature], the container for the indoor dataset.
It aggregates one or more thematic layers and may include inter-layer connections.

The `IndoorFeatures` table shall contain:

* `IndoorFeaturesID` as the primary key
* optionally, `layers` as a reference to associated thematic layers

NOTE: The `layers` column was added during schema correction because it was not included in the SQL generated from Enterprise Architecture tooling.

[[indoorfeature-schema]]
.A SQL schema of the IndoorFeatures table
[source,sql]
----
include::../schema/core/indoorfeatures.sql[]
----

[[indoorfeature-example]]
.An example INSERT statement for the IndoorFeatures table
[source,sql]
----
include::../examples/indoorfeatures.sql[]
----

[[req-indoorfeatures]]
[requirement]
.IndoorFeatures schema
====
[%metadata]
identifier:: /req/core/indoorfeature
part:: An `IndoorFeatures` table SHALL be related to at least one <<section-thematiclayer,`ThematicLayer`>> row through a foreign key.
====

[[section-thematiclayer]]
=== ThematicLayer

The `ThematicLayer` table stores instances of https://docs.ogc.org/is/22-045r5/22-045r5.html#subsection-tehmaticlayer[ThematicLayer], which represents one contextual decomposition of indoor space.

The `ThematicLayer` table shall contain:

* `ThematicLayerID` as the primary key
* `IndoorFeaturesID` as a foreign key to `IndoorFeatures`
* `semanticExtension` indicates whether there is an extension module with additional semantic information (mandatory)
* `theme` of type `ThemeLayerValue`, with values including "Virtual", "Physical", "Tags", and "Unknown" (mandatory)

[[thematiclayer-schema]]
.A SQL schema of the ThematicLayer table
[source,sql]
----
include::../schema/core/thematiclayer.sql[]
----

[[req-thematiclayer]]
[requirement]
.ThematicLayer schema
====
[%metadata]
identifier:: /req/core/thematiclayer
part:: A `ThematicLayer` table SHALL declare whether there is an extension module with additional semantic information using the `semanticExtension` column.
part:: A `ThematicLayer` table SHALL determine what type of model representation can be expected using the `theme` column.
part:: The `theme` value SHALL be one of "Virtual", "Physical", "Tags", and "Unknown".
====

[[section-primalspacelayer]]
=== PrimalSpaceLayer

The `PrimalSpaceLayer` table stores instances of https://docs.ogc.org/is/22-045r5/22-045r5.html#subsection-primalspacelayer[PrimalSpaceLayer], which contains spatial objects representing indoor subdivisions.

The `PrimalSpaceLayer` table shall contain:

* `PrimalSpaceLayerID` as the primary key
* `ThematicLayerID` as a foreign key to `ThematicLayer` (mandatory)
* optionally, `creationDate`
* optionally, `terminationDate`

[[primalspacelayer-schema]]
.A SQL schema of the PrimalSpaceLayer table
[source,sql]
----
include::../schema/core/primalspacelayer.sql[]
----

[[req-primalspacelayer]]
[requirement]
.PrimalSpaceLayer schema
====
[%metadata]
identifier:: /req/core/primalspacelayer
part:: A `PrimalSpaceLayer` table SHALL be related to one or more <<section-cellspace,CellSpace>> rows.
====

[[section-cellspace]]
=== CellSpace

The `CellSpace` table stores instances of https://docs.ogc.org/is/22-045r5/22-045r5.html#subsection-cellspace[CellSpace], which represents a unit of indoor space.

The `CellSpace` table shall contain:

* `CellSpaceID` as the primary key
* `PrimalSpaceLayerID` as a foreign key to `PrimalSpaceLayer`
* `PoI` is a flag that specifies whether this cell space is a point of interest (mandatory)
* `duality` referencing the `NodeID` of the dual node (mandatory)
* optionally, `cellSpaceName`
* optionally, `level`
* optionally, `cellSpaceGeom_Geometry2D` as a PostGIS `geometry` value (UML `CellSpaceGeometryType.Geometry2D`)
* optionally, `cellSpaceGeom_Geometry3D` as a PostGIS `geometry` value representing UML `GM_Solid` / `CellSpaceGeometryType.Geometry3D` as a closed boundary shell (`POLYHEDRALSURFACE Z` or `TIN Z`; see <<section-conventions>>)
* optionally, `externalReference` of composite type `ExternalReferenceType`

At most one of `cellSpaceGeom_Geometry2D` and `cellSpaceGeom_Geometry3D` is populated for a given row.
When `cellSpaceGeom_Geometry3D` is present, a `CHECK` constraint requires `GeometryType(...)` to be `POLYHEDRALSURFACE` or `TIN`.

[[cellspace-schema]]
.A SQL schema of the CellSpace table
[source,sql]
----
include::../schema/core/cellspace.sql[]
----

[[cellspace-example]]
.An example query returning CellSpace records
[source,sql]
----
include::../examples/select_cellspace.sql[]
----

[[req-cellspace]]
[requirement]
.CellSpace schema
====
[%metadata]
identifier:: /req/core/cellspace
part:: A `CellSpace` table SHALL declare whether it is a point of interest space using the `PoI` column.
part:: A `CellSpace` table SHALL contain a `duality` value referencing the `NodeID` of the corresponding <<section-node,Node>>.
part:: A `CellSpace` table SHALL NOT contain a row in which both `cellSpaceGeom_Geometry2D` and `cellSpaceGeom_Geometry3D` are non-null.
part:: A non-null `cellSpaceGeom_Geometry2D` value SHALL have the geometry type `POLYGON` or `MULTIPOLYGON`.
part:: A non-null `cellSpaceGeom_Geometry3D` value SHALL have the geometry type `POLYHEDRALSURFACE` or `TIN`.
====

[[section-cellboundary]]
=== CellBoundary

The `CellBoundary` table stores instances of https://docs.ogc.org/is/22-045r5/22-045r5.html#subsection-cellboundary[CellBoundary], a boundary of a CellSpace.
`CellBoundary` rows reference `CellSpace` rows through the `boundedBy` foreign key column.
Optionally, a `CellBoundary` may be the dual of an `Edge`; this association is encoded on the `Edge` table via the optional `Edge.duality` foreign key referencing `CellBoundaryID`.

The `CellBoundary` table shall contain:

* `CellBoundaryID` as the primary key
* `PrimalSpaceLayerID` as a foreign key to `PrimalSpaceLayer` (mandatory)
* `isVirtual` indicating whether the boundary is virtual or physical (mandatory)
* optionally, `boundedBy` referencing the `CellSpaceID` of a bounded cell space
* optionally, `cellBoundaryGeom_Geometry1D` as a PostGIS `geometry` value (UML `CellBoundaryGeometryType.Geometry1D`, typically a curve)
* optionally, `cellBoundaryGeom_Geometry2D` as a PostGIS `geometry` value (UML `CellBoundaryGeometryType.Geometry2D`, typically a surface)
* optionally, `externalReference` of composite type `ExternalReferenceType`

At most one of `cellBoundaryGeom_Geometry1D` and `cellBoundaryGeom_Geometry2D` is populated for a given row.

[[cellboundary-schema]]
.A SQL schema of the CellBoundary table
[source,sql]
----
include::../schema/core/cellboundary.sql[]
----

[[req-cellboundary]]
[requirement]
.CellBoundary schema
====
[%metadata]
identifier:: /req/core/cellboundary
part:: A `CellBoundary` table SHALL specify whether it is virtual using the `isVirtual` column.
part:: A `CellBoundary` table SHALL NOT contain a row in which both `cellBoundaryGeom_Geometry1D` and `cellBoundaryGeom_Geometry2D` are non-null.
part:: A non-null `cellBoundaryGeom_Geometry1D` value SHALL have the geometry type `LINESTRING` or `MULTILINESTRING`.
part:: A non-null `cellBoundaryGeom_Geometry2D` value SHALL have the geometry type `POLYGON` or `MULTIPOLYGON`.
====

[[section-dualspacelayer]]
=== DualSpaceLayer

The `DualSpaceLayer` table stores instances of https://docs.ogc.org/is/22-045r5/22-045r5.html#subsection-dualspacelayer[DualSpaceLayer], representing the graph structure corresponding to the primal space layer.

The `DualSpaceLayer` table shall contain:

* `DualSpaceLayerID` as the primary key
* `ThematicLayerID` as a foreign key to `ThematicLayer` (mandatory)
* `isLogical` indicating whether the graph is geometric or logical (mandatory)
* `isDirected` specifying whether the graph is directed (mandatory)
* optionally, `creationDate`
* optionally, `terminationDate`

[[dualspacelayer-schema]]
.A SQL schema of the DualSpaceLayer table
[source,sql]
----
include::../schema/core/dualspacelayer.sql[]
----

[[req-dualspacelayer]]
[requirement]
.DualSpaceLayer schema
====
[%metadata]
identifier:: /req/core/dualspacelayer
part:: A `DualSpaceLayer` table SHALL specify whether the provided graph is geometric or logical using the `isLogical` column.
part:: A `DualSpaceLayer` table SHALL specify whether the provided graph is directed using the `isDirected` column.
part:: A `DualSpaceLayer` table SHALL be related to one or more <<section-node,`Node`>> rows.
====

[[section-node]]
=== Node

The `Node` table stores instances of https://docs.ogc.org/is/22-045r5/22-045r5.html#subsection-node[Node], a state or graph vertex in the dual space layer.

The `Node` table shall contain:

* `NodeID` as the primary key
* `DualSpaceLayerID` as a foreign key to `DualSpaceLayer` (mandatory)
* `duality` referencing the `CellSpaceID` of the corresponding cell space (mandatory)
* optionally, `geometry` as a PostGIS `geometry` value (typically `Point`)
* optionally, `connects` as a `jsonb` array of connected `EdgeID` values

[[node-schema]]
.A SQL schema of the Node table
[source,sql]
----
include::../schema/core/node.sql[]
----

[[node-example]]
.An example query returning Node records
[source,sql]
----
include::../examples/select_node.sql[]
----

[[req-node]]
[requirement]
.Node schema
====
[%metadata]
identifier:: /req/core/node
part:: A `Node` table SHALL contain a `duality` value referencing the `CellSpaceID` of the corresponding <<section-cellspace,CellSpace>>.
part:: A `Node` table SHALL store connected edge identifiers in the `connects` column.
part:: A non-null `Node` `geometry` value SHALL have the geometry type `POINT`.
====

[[section-edge]]
=== Edge

The `Edge` table stores instances of https://docs.ogc.org/is/22-045r5/22-045r5.html#subsection-edge[Edge], representing a relationship between two nodes.

The `Edge` table shall contain:

* `EdgeID` as the primary key
* `DualSpaceLayerID` as a foreign key to `DualSpaceLayer` (mandatory)
* `weight` for use in graph-based applications (mandatory)
* `connects_node1` and `connects_node2` as foreign keys to the two connected `Node` rows (mandatory)
* optionally, `duality` referencing the `CellBoundaryID` of the corresponding cell boundary
* optionally, `geometry` as a PostGIS `geometry` value (typically `LineString`)

NOTE: If no list of connected edges is presented on `Node` (that is, `Node.connects` is absent or empty), the `Edge` table SHALL provide the connect properties `connects_node1` and `connects_node2` so that the dual-space graph adjacency can be determined from the `Edge` rows.

[[edge-schema]]
.A SQL schema of the Edge table
[source,sql]
----
include::../schema/core/edge.sql[]
----

[[req-edge]]
[requirement]
.Edge schema
====
[%metadata]
identifier:: /req/core/edge
part:: An `Edge` table SHALL reference connected <<section-node,Nodes>> using the `connects_node1` and `connects_node2` columns.
part:: An `Edge` table SHALL contain a `weight` column.
part:: A non-null `Edge` `geometry` value SHALL have the geometry type `LINESTRING` or `MULTILINESTRING`.
====

[[section-interlayerconnection]]
=== InterLayerConnection

The `InterLayerConnection` table stores instances of https://docs.ogc.org/is/22-045r5/22-045r5.html#subsection-interlayerconnection[InterLayerConnection], representing a relationship between objects in different thematic layers.

The `InterLayerConnection` table shall contain:

* `InterLayerConnectionID` as the primary key
* `IndoorFeaturesID` as a foreign key to `IndoorFeatures`
* `typeOfTopoExpression` of type `TopoExpressionValue`, with values including "Contains", "Overlaps", "Equals", "Within", "Crosses", and "Other" (mandatory)
* optionally, `comment`

Associated junction tables `InterLayerConnection_ThematicLayer`, `InterLayerConnection_Node`, and `InterLayerConnection_CellSpace` store references to thematic layers, nodes, and cell spaces respectively.
They are split into three tables so that each many-to-many association targets a single feature class with a typed foreign key, rather than mixing heterogeneous identifiers in one column or array.

[[interlayerconnection-schema]]
.A SQL schema of the InterLayerConnection table
[source,sql]
----
include::../schema/core/interlayerconnection.sql[]
----

[[interlayerconnection-cellspace-schema]]
.A SQL schema of the InterLayerConnection_CellSpace junction table
[source,sql]
----
include::../schema/core/interlayerconnection_cellspace.sql[]
----

[[interlayerconnection-node-schema]]
.A SQL schema of the InterLayerConnection_Node junction table
[source,sql]
----
include::../schema/core/interlayerconnection_node.sql[]
----

[[interlayerconnection-thematiclayer-schema]]
.A SQL schema of the InterLayerConnection_ThematicLayer junction table
[source,sql]
----
include::../schema/core/interlayerconnection_thematiclayer.sql[]
----

[[req-interlayerconnection]]
[requirement]
.InterLayerConnection schema
====
[%metadata]
identifier:: /req/core/interlayerconnection
part:: An `InterLayerConnection` table SHALL reference <<section-thematiclayer,ThematicLayer>> rows through the `InterLayerConnection_ThematicLayer` junction table.
====

[[section-externalreference]]
=== ExternalReferenceType

The UML DataTypes `ExternalObjectReferenceType` and `ExternalReferenceType` are encoded as PostgreSQL composite types rather than as tables.
These are not feature classes of IndoorGML 2.0.
`CellSpace` and `CellBoundary` optionally store an `externalReference` column of type `ExternalReferenceType`, which nests an `externalObject` of type `ExternalObjectReferenceType` together with an `informationSystem` URI.

[[externalreferencetype-schema]]
.A SQL schema of the ExternalReference composite types
[source,sql]
----
include::../schema/core/externalreferencetype.sql[]
----
