[appendix,obligation="normative"]
== Conformance Class Abstract Test Suite

=== Conformance Class Core
[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/indoorgml-2/2.0/conf/sql/core
target:: http://www.opengis.net/spec/indoorgml-2/2.0/sql/req/core
classification:: Target Type:Implementation Specification
abstract-test:: /conf/core/indoorsql
abstract-test:: /conf/core/indoorfeature
abstract-test:: /conf/core/thematiclayer
abstract-test:: /conf/core/primalspacelayer
abstract-test:: /conf/core/cellspace
abstract-test:: /conf/core/cellboundary
abstract-test:: /conf/core/dualspacelayer
abstract-test:: /conf/core/node
abstract-test:: /conf/core/edge
abstract-test:: /conf/core/interlayerconnection
====

[abstract_test]
====
[%metadata]
identifier:: /conf/core/indoorsql
target:: /req/core/indoorsql
test-purpose:: Verify that each feature table of the SQL encoding contains a string primary key column for the feature identifier.
test-method:: Inspect the database schema to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/core/indoorfeature
target:: /req/core/indoorfeature
test-purpose:: Verify that an `IndoorFeatures` table is related to at least one `ThematicLayer` row through a foreign key.
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/core/thematiclayer
target:: /req/core/thematiclayer
test-purpose:: For the following columns of the `ThematicLayer` table, verify that:
+
--
* The `semanticExtension` column declares whether there is an extension module with additional semantic information. +
* The `theme` column determines what type of model representation can be expected. +
* The `theme` value is one of "Virtual", "Physical", "Tags", and "Unknown".
--
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/core/primalspacelayer
target:: /req/core/primalspacelayer
test-purpose:: Verify that a `PrimalSpaceLayer` table is related to one or more `CellSpace` rows.
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/core/cellspace
target:: /req/core/cellspace
test-purpose:: For the following columns of the `CellSpace` table, verify that:
+
--
* The `PoI` column declares whether it is a point of interest space. +
* The `duality` column references the `NodeID` of the corresponding `Node`. +
* No row has both `cellSpaceGeom_Geometry2D` and `cellSpaceGeom_Geometry3D` non-null. +
* Every non-null `cellSpaceGeom_Geometry2D` value has the geometry type `POLYGON` or `MULTIPOLYGON`. +
* Every non-null `cellSpaceGeom_Geometry3D` value has the geometry type `POLYHEDRALSURFACE` or `TIN`.
--
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/core/cellboundary
target:: /req/core/cellboundary
test-purpose:: For the following columns of the `CellBoundary` table, verify that:
+
--
* The `isVirtual` column specifies whether the boundary is virtual. +
* No row has both `cellBoundaryGeom_Geometry1D` and `cellBoundaryGeom_Geometry2D` non-null. +
* Every non-null `cellBoundaryGeom_Geometry1D` value has the geometry type `LINESTRING` or `MULTILINESTRING`. +
* Every non-null `cellBoundaryGeom_Geometry2D` value has the geometry type `POLYGON` or `MULTIPOLYGON`.
--
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/core/dualspacelayer
target:: /req/core/dualspacelayer
test-purpose:: For the following columns and associations of the `DualSpaceLayer` table, verify that:
+
--
* The `isLogical` column specifies whether the provided graph is geometric or logical. +
* The `isDirected` column specifies whether the provided graph is directed. +
* The `DualSpaceLayer` table is related to one or more `Node` rows.
--
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/core/node
target:: /req/core/node
test-purpose:: For the following columns of the `Node` table, verify that:
+
--
* The `duality` column references the `CellSpaceID` of the corresponding `CellSpace`. +
* Connected edge identifiers are stored in the `connects` column. +
* Every non-null `geometry` value has the geometry type `POINT`.
--
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/core/edge
target:: /req/core/edge
test-purpose:: For the following columns of the `Edge` table, verify that:
+
--
* Connected `Node` rows are referenced using the `connects_node1` and `connects_node2` columns. +
* A `weight` column is present. +
* Every non-null `geometry` value has the geometry type `LINESTRING` or `MULTILINESTRING`.
--
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/core/interlayerconnection
target:: /req/core/interlayerconnection
test-purpose:: Verify that an `InterLayerConnection` table references `ThematicLayer` rows through the `InterLayerConnection_ThematicLayer` junction table.
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

=== Conformance Class Navigation
[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/indoorgml-2/2.0/conf/sql/navi
target:: http://www.opengis.net/spec/indoorgml-2/2.0/sql/req/navi
classification:: Target Type:Implementation Specification
abstract-test:: /conf/navi/navigablespace
abstract-test:: /conf/navi/generalspace
abstract-test:: /conf/navi/transferspace
abstract-test:: /conf/navi/objectspace
abstract-test:: /conf/navi/navigableboundary
abstract-test:: /conf/navi/route
====

[abstract_test]
====
[%metadata]
identifier:: /conf/navi/navigablespace
target:: /req/navi/navigablespace
test-purpose:: Verify that a `NavigableSpace` table references a `CellSpace` row and contains a `locomotionType` column.
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/navi/generalspace
target:: /req/navi/generalspace
test-purpose:: Verify that a `GeneralSpace` table contains a `function` column.
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/navi/transferspace
target:: /req/navi/transferspace
test-purpose:: Verify that a `TransferSpace` table contains `category` and `function` columns.
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/navi/objectspace
target:: /req/navi/objectspace
test-purpose:: Verify that an `ObjectSpace` table references a `NonNavigableSpace` row.
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/navi/navigableboundary
target:: /req/navi/navigableboundary
test-purpose:: Verify that a `NavigableBoundary` table contains a `NavigableBoundaryFunction` column.
test-method:: Inspect the database schema and instance data to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/navi/route
target:: /req/navi/route
test-purpose:: For the following columns of the `Route` table, verify that:
+
--
* Ordered node identifiers are stored in the `routeNode` column. +
* Ordered edge identifiers are stored in the `routeEdge` column.
--
test-method:: Inspect the database schema and instance data to verify the above requirement.
====
