= Standard template in Metanorma

The base template was taken from the GitHub project below:

* https://github.com/metanorma/mn-templates-ogc

The OGC IndoorGML 2.0 build results can be shown as below links:

* https://htmlpreview.github.io/?https://github.com/opengeospatial/IndoorGML-SWG/blob/master/IndoorGML2/IndoorGML2_metanorma/document.html[OGC_22-045.html]
* https://github.com/opengeospatial/IndoorGML-SWG/blob/master/IndoorGML2/IndoorGML2_metanorma/document.pdf[OGC_22-045.pdf]

== Content

This repository contains the content for an OGC standard.

* `document.adoc` - the main standard document with references to all sections
* remaining ``adoc``s - each section of the standard document is in a separate document: follow directions in each document to populate
* `figures` - figures go here
* `images` - Image files for graphics go here. Image files for figures go in the `figures` directory. Only place in here images not used in figures (e.g., as parts of tables, as logos, etc.)
* `requirements` - directory for requirements and requirement classes to be referenced in `clause_7_normative_text.adoc`
* `code` - sample code to accompany the standard, if desired
* `abstract_tests` - the Abstract Test Suite comprising one test for every requirement, optional
* `UML` - UML diagrams, if applicable

== Building (in your local system)

. (If you haven't installed Docker) Install the https://www.docker.com/products/docker-desktop/[Docker Desktop].

. Pull the Metanorma Docker container (ref: https://www.metanorma.org/install/docker/).
+
```
docker pull metanorma/metanorma
```

. Building Document
+
```
git clone https://github.com/opengeospatial/IndoorGML-SWG.git

cd IndoorGML2/IndoorGML2_metanorma

docker run -v "$(pwd)":/metanorma -v ${HOME}/.fontist/fonts/:/config/fonts  metanorma/metanorma metanorma compile --agree-to-terms -t ogc -x html,pdf document.adoc
```

// TODO-1: add more detailed information
// TODO-1.1: How to edit (with tools)
// TODO-2: UML Figure regenerated (needs refine)
// TODO-3: For requirement and conformance classes, needs to define dependencies
// TODO-3.1: For ATS, do we need to add "test purpose"?
// TODO-4: Make GitHub Action for automate building document
