<?xml version="1.0" encoding="UTF-8"?>
<schema
    xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:core="http://www.opengis.net/indoorgml/2.0/core"
	xmlns:gmd="http://www.isotc211.org/2005/gmd"
	xmlns:gml="http://www.opengis.net/gml/3.2"
	elementFormDefault="qualified"
	targetNamespace="http://www.opengis.net/indoorgml/2.0/core"
	version="2.0">
  <annotation>
    <appinfo>
      <gml:gmlProfileSchema>IndoorGML</gml:gmlProfileSchema>
    </appinfo>
  </annotation>
  <import namespace="http://www.isotc211.org/2005/gmd" schemaLocation="http://schemas.opengis.net/iso/19139/20070417/gmd/gmd.xsd"/>
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
  <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
  <element name="CellBoundary" substitutionGroup="gml:AbstractFeature" type="core:CellBoundaryType"/>
  <complexType name="CellBoundaryType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element minOccurs="0" name="cellBoundaryGeom" type="core:CellBoundaryGeometryPropertyType"/>
          <element minOccurs="0" name="externalReference" type="core:ExternalReferencePropertyType"/>
          <element name="isVirtual" type="boolean"/>
          <element minOccurs="0" name="duality" type="core:EdgePropertyType">
            <annotation>
              <documentation>Corresponding cell boundary in the primal space</documentation>
              <appinfo>
                <gml:reversePropertyName>core:duality</gml:reversePropertyName>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="CellBoundaryPropertyType">
    <sequence minOccurs="0">
      <element ref="core:CellBoundary"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="CellBoundaryGeometry" substitutionGroup="gml:AbstractObject" type="core:CellBoundaryGeometryType"/>
  <complexType name="CellBoundaryGeometryType">
    <sequence>
      <element minOccurs="0" name="Geometry2D" type="gml:SurfacePropertyType"/>
      <element minOccurs="0" name="Geometry1D" type="gml:CurvePropertyType"/>
    </sequence>
  </complexType>
  <complexType name="CellBoundaryGeometryPropertyType">
    <sequence>
      <element ref="core:CellBoundaryGeometry"/>
    </sequence>
  </complexType>
  <element name="CellSpace" substitutionGroup="gml:AbstractFeature" type="core:CellSpaceType"/>
  <complexType name="CellSpaceType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element minOccurs="0" name="cellSpaceGeom" type="core:CellSpaceGeometryPropertyType"/>
          <element minOccurs="0" name="externalReference" type="core:ExternalReferencePropertyType"/>
          <element minOccurs="0" name="level" type="string"/>
          <element name="PoI" type="boolean"/>
          <element minOccurs="0" name="cellSpaceName" type="string"/>
          <element minOccurs="0" name="duality" type="core:NodePropertyType">
            <annotation>
              <documentation>Corresponding cell space in the primal space</documentation>
              <appinfo>
                <gml:reversePropertyName>core:duality</gml:reversePropertyName>
              </appinfo>
            </annotation>
          </element>
          <element maxOccurs="unbounded" minOccurs="0" name="boundedBy" type="core:CellBoundaryPropertyType">
            <annotation>
              <documentation>Cell boundaries that are bounding a cell space</documentation>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="CellSpacePropertyType">
    <sequence minOccurs="0">
      <element ref="core:CellSpace"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="CellSpaceGeometry" substitutionGroup="gml:AbstractObject" type="core:CellSpaceGeometryType"/>
  <complexType name="CellSpaceGeometryType">
    <sequence>
      <element minOccurs="0" name="Geometry3D" type="gml:SolidPropertyType"/>
      <element minOccurs="0" name="Geometry2D" type="gml:SurfacePropertyType"/>
    </sequence>
  </complexType>
  <complexType name="CellSpaceGeometryPropertyType">
    <sequence>
      <element ref="core:CellSpaceGeometry"/>
    </sequence>
  </complexType>
  <element name="DualSpaceLayer" substitutionGroup="gml:AbstractFeature" type="core:DualSpaceLayerType"/>
  <complexType name="DualSpaceLayerType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="isLogical" type="boolean"/>
          <element minOccurs="0" name="creationDate" type="dateTime"/>
          <element minOccurs="0" name="terminationDate" type="dateTime"/>
          <element name="isDirected" type="boolean"/>
          <element maxOccurs="unbounded" minOccurs="0" name="edgeMember">
            <annotation>
              <documentation>Edges of a dual space</documentation>
            </annotation>
            <complexType>
              <complexContent>
                <extension base="gml:AbstractFeatureMemberType">
                  <sequence minOccurs="0">
                    <element ref="core:Edge"/>
                  </sequence>
                  <attributeGroup ref="gml:AssociationAttributeGroup"/>
                </extension>
              </complexContent>
            </complexType>
          </element>
          <element maxOccurs="unbounded" name="nodeMember">
            <annotation>
              <documentation>Nodes of a dual space</documentation>
            </annotation>
            <complexType>
              <complexContent>
                <extension base="gml:AbstractFeatureMemberType">
                  <sequence minOccurs="0">
                    <element ref="core:Node"/>
                  </sequence>
                  <attributeGroup ref="gml:AssociationAttributeGroup"/>
                </extension>
              </complexContent>
            </complexType>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="DualSpaceLayerPropertyType">
    <sequence minOccurs="0">
      <element ref="core:DualSpaceLayer"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="Edge" substitutionGroup="gml:AbstractFeature" type="core:EdgeType"/>
  <complexType name="EdgeType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element minOccurs="0" name="geometry" type="gml:CurvePropertyType"/>
          <element name="weight" type="double"/>
          <element minOccurs="0" name="duality" type="core:CellBoundaryPropertyType">
            <annotation>
              <documentation>Corresponding edge in the dual space</documentation>
              <appinfo>
                <gml:reversePropertyName>core:duality</gml:reversePropertyName>
              </appinfo>
            </annotation>
          </element>
          <element maxOccurs="2" minOccurs="2" name="connects" type="core:NodePropertyType">
            <annotation>
              <documentation>The two nodes connected by an edge</documentation>
              <appinfo>
                <gml:reversePropertyName>core:connects</gml:reversePropertyName>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="EdgePropertyType">
    <sequence minOccurs="0">
      <element ref="core:Edge"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="ExternalObjectReference" substitutionGroup="gml:AbstractObject" type="core:ExternalObjectReferenceType"/>
  <complexType name="ExternalObjectReferenceType">
    <sequence>
      <element name="name" type="string"/>
      <element name="uri" type="anyURI"/>
    </sequence>
  </complexType>
  <complexType name="ExternalObjectReferencePropertyType">
    <sequence>
      <element ref="core:ExternalObjectReference"/>
    </sequence>
  </complexType>
  <element name="ExternalReference" substitutionGroup="gml:AbstractObject" type="core:ExternalReferenceType"/>
  <complexType name="ExternalReferenceType">
    <sequence>
      <element name="externalObject" type="core:ExternalObjectReferencePropertyType"/>
      <element name="informationSystem" type="gmd:URL_PropertyType"/>
    </sequence>
  </complexType>
  <complexType name="ExternalReferencePropertyType">
    <sequence>
      <element ref="core:ExternalReference"/>
    </sequence>
  </complexType>
  <element name="IndoorFeatures" substitutionGroup="gml:AbstractFeature" type="core:IndoorFeaturesType"/>
  <complexType name="IndoorFeaturesType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element maxOccurs="unbounded" name="layers">
            <complexType>
              <complexContent>
                <extension base="gml:AbstractFeatureMemberType">
                  <sequence minOccurs="0">
                    <element ref="core:ThematicLayer"/>
                  </sequence>
                  <attributeGroup ref="gml:AssociationAttributeGroup"/>
                </extension>
              </complexContent>
            </complexType>
          </element>
          <element maxOccurs="unbounded" minOccurs="0" name="layerConnections">
            <complexType>
              <complexContent>
                <extension base="gml:AbstractFeatureMemberType">
                  <sequence minOccurs="0">
                    <element ref="core:InterLayerConnection"/>
                  </sequence>
                  <attributeGroup ref="gml:AssociationAttributeGroup"/>
                </extension>
              </complexContent>
            </complexType>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="IndoorFeaturesPropertyType">
    <sequence minOccurs="0">
      <element ref="core:IndoorFeatures"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="InterLayerConnection" substitutionGroup="gml:AbstractFeature" type="core:InterLayerConnectionType">
    <annotation>
      <documentation>Describes the connection between two thematic layers.</documentation>
    </annotation>
  </element>
  <complexType name="InterLayerConnectionType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="typeOfTopoExpression" type="core:TopoExpressionValueType">
            <annotation>
              <documentation>Describes the topological relationship between two layers (e.g. overlaps, contains, etc.).</documentation>
            </annotation>
          </element>
          <element minOccurs="0" name="comment" type="string"/>
          <element maxOccurs="2" minOccurs="2" name="connectedLayers" type="core:ThematicLayerPropertyType"/>
          <element maxOccurs="2" minOccurs="0" name="connectedCells" type="core:CellSpacePropertyType">
            <annotation>
              <documentation>Indicates the interconnected primal spaces</documentation>
            </annotation>
          </element>
          <element maxOccurs="2" minOccurs="0" name="connectedNodes" type="core:NodePropertyType">
            <annotation>
              <documentation>Indicates the interconnected dual spaces</documentation>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="InterLayerConnectionPropertyType">
    <sequence minOccurs="0">
      <element ref="core:InterLayerConnection"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="Node" substitutionGroup="gml:AbstractFeature" type="core:NodeType"/>
  <complexType name="NodeType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element minOccurs="0" name="geometry" type="gml:PointPropertyType"/>
          <element name="duality" type="core:CellSpacePropertyType">
            <annotation>
              <documentation>Corresponding node in the dual space</documentation>
              <appinfo>
                <gml:reversePropertyName>core:duality</gml:reversePropertyName>
              </appinfo>
            </annotation>
          </element>
          <element maxOccurs="unbounded" minOccurs="0" name="connects" type="core:EdgePropertyType">
            <annotation>
              <documentation>Edges connected to the node</documentation>
              <appinfo>
                <gml:reversePropertyName>core:connects</gml:reversePropertyName>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="NodePropertyType">
    <sequence minOccurs="0">
      <element ref="core:Node"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="PrimalSpaceLayer" substitutionGroup="gml:AbstractFeature" type="core:PrimalSpaceLayerType"/>
  <complexType name="PrimalSpaceLayerType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element minOccurs="0" name="creationDate" type="dateTime"/>
          <element minOccurs="0" name="terminationDate" type="dateTime"/>
          <element maxOccurs="unbounded" name="cellSpaceMember">
            <annotation>
              <documentation>Cell spaces of a primal space</documentation>
            </annotation>
            <complexType>
              <complexContent>
                <extension base="gml:AbstractFeatureMemberType">
                  <sequence minOccurs="0">
                    <element ref="core:CellSpace"/>
                  </sequence>
                  <attributeGroup ref="gml:AssociationAttributeGroup"/>
                </extension>
              </complexContent>
            </complexType>
          </element>
          <element maxOccurs="unbounded" minOccurs="0" name="cellBoundaryMember">
            <annotation>
              <documentation>Cell boundaries of a primal space</documentation>
            </annotation>
            <complexType>
              <complexContent>
                <extension base="gml:AbstractFeatureMemberType">
                  <sequence minOccurs="0">
                    <element ref="core:CellBoundary"/>
                  </sequence>
                  <attributeGroup ref="gml:AssociationAttributeGroup"/>
                </extension>
              </complexContent>
            </complexType>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="PrimalSpaceLayerPropertyType">
    <sequence minOccurs="0">
      <element ref="core:PrimalSpaceLayer"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="ThematicLayer" substitutionGroup="gml:AbstractFeature" type="core:ThematicLayerType">
    <annotation>
      <documentation>A layer of specific theme aggregating a primal and/or a dual space of a given environment.</documentation>
    </annotation>
  </element>
  <complexType name="ThematicLayerType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="semanticExtension" type="boolean">
            <annotation>
              <documentation>Indicates whether semantic information is associated (true) or not (false) to the primal space of the thematic layer.</documentation>
            </annotation>
          </element>
          <element name="theme" type="core:ThemeLayerValueType">
            <annotation>
              <documentation>Determines the theme of the layer (e.g., topographic, logical, etc.).</documentation>
            </annotation>
          </element>
          <element minOccurs="0" name="primalSpace">
            <annotation>
              <documentation>Relates the primal spaces to the thematicLayer</documentation>
            </annotation>
            <complexType>
              <complexContent>
                <extension base="gml:AbstractFeatureMemberType">
                  <sequence minOccurs="0">
                    <element ref="core:PrimalSpaceLayer"/>
                  </sequence>
                  <attributeGroup ref="gml:AssociationAttributeGroup"/>
                </extension>
              </complexContent>
            </complexType>
          </element>
          <element minOccurs="0" name="dualSpace">
            <annotation>
              <documentation>Relates the dual spaces to the thematicLayer.</documentation>
            </annotation>
            <complexType>
              <complexContent>
                <extension base="gml:AbstractFeatureMemberType">
                  <sequence minOccurs="0">
                    <element ref="core:DualSpaceLayer"/>
                  </sequence>
                  <attributeGroup ref="gml:AssociationAttributeGroup"/>
                </extension>
              </complexContent>
            </complexType>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="ThematicLayerPropertyType">
    <sequence minOccurs="0">
      <element ref="core:ThematicLayer"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <simpleType name="ThemeLayerValueType">
    <union memberTypes="core:ThemeLayerValueEnumerationType core:ThemeLayerValueOtherType"/>
  </simpleType>
  <simpleType name="ThemeLayerValueEnumerationType">
    <restriction base="string">
      <enumeration value="Tags"/>
      <enumeration value="Virtual"/>
      <enumeration value="Unknown"/>
      <enumeration value="Physical"/>
    </restriction>
  </simpleType>
  <simpleType name="ThemeLayerValueOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <simpleType name="TopoExpressionValueType">
    <union memberTypes="core:TopoExpressionValueEnumerationType core:TopoExpressionValueOtherType"/>
  </simpleType>
  <simpleType name="TopoExpressionValueEnumerationType">
    <restriction base="string">
      <enumeration value="Contains"/>
      <enumeration value="Overlaps"/>
      <enumeration value="Equals"/>
      <enumeration value="Within"/>
      <enumeration value="Crosses"/>
      <enumeration value="Other"/>
    </restriction>
  </simpleType>
  <simpleType name="TopoExpressionValueOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
</schema>
