<?xml version="1.0" encoding="UTF-8"?>
<schema
    xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:navi="http://www.opengis.net/indoorgml/2.0/navi"
	xmlns:core="http://www.opengis.net/indoorgml/2.0/core"
	xmlns:gml="http://www.opengis.net/gml/3.2"
	elementFormDefault="qualified"
	targetNamespace="http://www.opengis.net/indoorgml/2.0/navi"
	version="2.0">
  <annotation>
    <appinfo>
      <gml:gmlProfileSchema>IndoorGML</gml:gmlProfileSchema>
    </appinfo>
  </annotation>
  <import namespace="http://www.isotc211.org/2005/gmd" schemaLocation="http://schemas.opengis.net/iso/19139/20070417/gmd/gmd.xsd"/>
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
  <import namespace="http://www.opengis.net/indoorgml/2.0/core" schemaLocation="IndoorGML_core.xsd"/>
  <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
  <element name="GeneralSpace" substitutionGroup="navi:NavigableSpace" type="navi:GeneralSpaceType"/>
  <complexType name="GeneralSpaceType">
    <complexContent>
      <extension base="navi:NavigableSpaceType">
        <sequence>
          <element name="function" type="navi:GeneralSpaceFunctionType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="GeneralSpacePropertyType">
    <sequence minOccurs="0">
      <element ref="navi:GeneralSpace"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <simpleType name="GeneralSpaceFunctionType">
    <union memberTypes="navi:GeneralSpaceFunctionEnumerationType navi:GeneralSpaceFunctionOtherType"/>
  </simpleType>
  <simpleType name="GeneralSpaceFunctionEnumerationType">
    <restriction base="string">
      <enumeration value="Administration"/>
      <enumeration value="Business, trade"/>
      <enumeration value="Education, training"/>
      <enumeration value="Recreation"/>
      <enumeration value="Laboratory"/>
      <enumeration value="Storage"/>
      <enumeration value="Security"/>
    </restriction>
  </simpleType>
  <simpleType name="GeneralSpaceFunctionOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <simpleType name="LocomotionAccessType">
    <union memberTypes="navi:LocomotionAccessEnumerationType navi:LocomotionAccessOtherType"/>
  </simpleType>
  <simpleType name="LocomotionAccessEnumerationType">
    <restriction base="string">
      <enumeration value="Walking"/>
      <enumeration value="Flying"/>
      <enumeration value="Rolling"/>
      <enumeration value="Unspecified"/>
    </restriction>
  </simpleType>
  <simpleType name="LocomotionAccessOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <element name="NavigableBoundary" substitutionGroup="core:CellBoundary" type="navi:NavigableBoundaryType"/>
  <complexType name="NavigableBoundaryType">
    <complexContent>
      <extension base="core:CellBoundaryType">
        <sequence>
          <element name="NavigableBoundaryFunction" type="navi:NavigableBoundaryFunctionType"/>
          <element minOccurs="0" name="boundaryOrientation" type="boolean"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="NavigableBoundaryPropertyType">
    <sequence minOccurs="0">
      <element ref="navi:NavigableBoundary"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <simpleType name="NavigableBoundaryFunctionType">
    <union memberTypes="navi:NavigableBoundaryFunctionEnumerationType navi:NavigableBoundaryFunctionOtherType"/>
  </simpleType>
  <simpleType name="NavigableBoundaryFunctionEnumerationType">
    <restriction base="string">
      <enumeration value="AnchorBoundary"/>
      <enumeration value="ConnectionBoundary"/>
    </restriction>
  </simpleType>
  <simpleType name="NavigableBoundaryFunctionOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <element name="NavigableSpace" substitutionGroup="core:CellSpace" type="navi:NavigableSpaceType"/>
  <complexType name="NavigableSpaceType">
    <complexContent>
      <extension base="core:CellSpaceType">
        <sequence>
          <element name="locomotionType" type="navi:LocomotionAccessType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="NavigableSpacePropertyType">
    <sequence minOccurs="0">
      <element ref="navi:NavigableSpace"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="NonNavigableBoundary" substitutionGroup="core:CellBoundary" type="navi:NonNavigableBoundaryType"/>
  <complexType name="NonNavigableBoundaryType">
    <complexContent>
      <extension base="core:CellBoundaryType">
        <sequence/>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="NonNavigableBoundaryPropertyType">
    <sequence minOccurs="0">
      <element ref="navi:NonNavigableBoundary"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="NonNavigableSpace" substitutionGroup="core:CellSpace" type="navi:NonNavigableSpaceType"/>
  <complexType name="NonNavigableSpaceType">
    <complexContent>
      <extension base="core:CellSpaceType">
        <sequence/>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="NonNavigableSpacePropertyType">
    <sequence minOccurs="0">
      <element ref="navi:NonNavigableSpace"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="ObjectSpace" substitutionGroup="navi:NonNavigableSpace" type="navi:ObjectSpaceType"/>
  <complexType name="ObjectSpaceType">
    <complexContent>
      <extension base="navi:NonNavigableSpaceType">
        <sequence>
          <element minOccurs="0" name="description" type="string"/>
          <element minOccurs="0" name="containedFeatures" type="integer"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="ObjectSpacePropertyType">
    <sequence minOccurs="0">
      <element ref="navi:ObjectSpace"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="Route" substitutionGroup="gml:AbstractFeature" type="navi:RouteType"/>
  <complexType name="RouteType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element minOccurs="0" name="creationDate" type="dateTime"/>
          <element maxOccurs="unbounded" minOccurs="2" name="routeNode" type="core:NodePropertyType"/>
          <element maxOccurs="unbounded" name="routeEdge" type="core:EdgePropertyType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="RoutePropertyType">
    <sequence minOccurs="0">
      <element ref="navi:Route"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <simpleType name="TransferSpaceType">
    <union memberTypes="navi:TransferSpaceEnumerationType navi:TransferSpaceOtherType"/>
  </simpleType>
  <simpleType name="TransferSpaceEnumerationType">
    <restriction base="string">
      <enumeration value="Door"/>
      <enumeration value="Window"/>
    </restriction>
  </simpleType>
  <simpleType name="TransferSpaceOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <element name="TransferSpace" substitutionGroup="navi:NavigableSpace" type="navi:TransferSpaceType"/>
  <complexType name="TransferSpaceType">
    <complexContent>
      <extension base="navi:NavigableSpaceType">
        <sequence>
          <element name="function" type="navi:TransferSpaceFunctionType"/>
          <element name="type" type="navi:TransferSpaceType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="TransferSpacePropertyType">
    <sequence minOccurs="0">
      <element ref="navi:TransferSpace"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <simpleType name="TransferSpaceFunctionType">
    <union memberTypes="navi:TransferSpaceFunctionEnumerationType navi:TransferSpaceFunctionOtherType"/>
  </simpleType>
  <simpleType name="TransferSpaceFunctionEnumerationType">
    <restriction base="string">
      <enumeration value="ConnectionSpace"/>
      <enumeration value="AnchorSpace"/>
    </restriction>
  </simpleType>
  <simpleType name="TransferSpaceFunctionOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
</schema>
