
== Conventions

// [NOTE]
// ====
// This section provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.
// ====
=== Symbols (and abbreviated terms)

The following symbols and abbreviated terms are used in this standard.
Symbols and abbreviated terms defined in <<ogc22-045r5,IndoorGML 2.0 Part 1>> also apply to this document.

[[symbols]]
.Symbols and abbreviated terms
[]
|===
h| *Abbreviation* h| *Word or Phrase*
| IndoorGML  | Indoor Geographic Markup Language
| IndoorJSON | JSON encoding of IndoorGML concepts
| JSON       | JavaScript Object Notation
| OGC        | Open Geospatial Consortium
| UML        | Unified Modeling Language
| 1D         | One Dimensional
| 2D         | Two Dimensional
| 3D         | Three Dimensional
|===

=== Identifiers

The normative provisions in this standard are denoted by the URI 

`http://www.opengis.net/spec/indoorgml-2/2.0/json`

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.


=== Use of JSON terminology

The following terms are used as specified in <<rfc8259,JSON>>. In particular:

* "member" refers to a name/value pair of an object;
* "key" refers to the name of a member; and
* "value" refers to the value of a member, which may be an object, array, string, number, boolean, or `null`.

For example, the GeoJSON "geometry" member has the key "geometry" and one of the GeoJSON geometries (or `null`) as its value.
