/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 07-Jul-2025 11:10:23 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

CREATE EXTENSION IF NOT EXISTS postgis
;
CREATE EXTENSION IF NOT EXISTS postgis_sfcgal
;
/* Drop Tables */

DROP TABLE IF EXISTS "CellBoundary" CASCADE
;

DROP TABLE IF EXISTS "CellBoundaryGeometryType" CASCADE
;

DROP TABLE IF EXISTS "CellSpace" CASCADE
;

DROP TABLE IF EXISTS "CellSpaceGeometryType" CASCADE
;

DROP TABLE IF EXISTS "DualSpaceLayer" CASCADE
;

DROP TABLE IF EXISTS "Edge" CASCADE
;

DROP TABLE IF EXISTS "IndoorFeatures" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection_CellSpace" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection_Node" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection_ThematicLayer" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection CellSpace" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection Node" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection ThematicLayer" CASCADE
;

DROP TABLE IF EXISTS "Node" CASCADE
;

DROP TABLE IF EXISTS "PrimalSpaceLayer" CASCADE
;

DROP TABLE IF EXISTS "ThematicLayer" CASCADE
;

/* Drop ENUM and composite Types */

DROP TYPE IF EXISTS "TopoExpressionValue" CASCADE
;

DROP TYPE IF EXISTS "ThemeLayerValue" CASCADE
;

DROP TYPE IF EXISTS "ExternalReferenceType" CASCADE
;

DROP TYPE IF EXISTS "ExternalObjectReferenceType" CASCADE
;

/* Create ENUM Types */

CREATE TYPE "ThemeLayerValue" AS ENUM (
	'Virtual',
	'Physical',
	'Tags',
	'Unknown'
)
;

CREATE TYPE "TopoExpressionValue" AS ENUM (
	'Contains',
	'Overlaps',
	'Equals',
	'Within',
	'Crosses',
	'Other'
)
;

/* Create composite Types (UML DataTypes for external references) */

CREATE TYPE "ExternalObjectReferenceType" AS (
	"name" varchar(100),
	"uri" text
)
;

CREATE TYPE "ExternalReferenceType" AS (
	"externalObject" "ExternalObjectReferenceType",
	"informationSystem" text
)
;

/* Create Tables */

CREATE TABLE "CellBoundary"
(
	"cellBoundaryGeom_Geometry1D" geometry NULL,
	"cellBoundaryGeom_Geometry2D" geometry NULL,
	"externalReference" "ExternalReferenceType" NULL,
	"isVirtual" boolean NOT NULL,
	"CellBoundaryID" varchar(100) NOT NULL,
	"boundedBy" varchar(100) NULL,
	"PrimalSpaceLayerID" varchar(100) NOT NULL,
	CONSTRAINT "chk_CellBoundary_geom1d_curve" CHECK (
		"cellBoundaryGeom_Geometry1D" IS NULL
		OR GeometryType("cellBoundaryGeom_Geometry1D") IN ('LINESTRING', 'MULTILINESTRING')
	),
	CONSTRAINT "chk_CellBoundary_geom2d_surface" CHECK (
		"cellBoundaryGeom_Geometry2D" IS NULL
		OR GeometryType("cellBoundaryGeom_Geometry2D") IN ('POLYGON', 'MULTIPOLYGON')
	)
)
;

CREATE TABLE "CellSpace"
(
	"cellSpaceGeom_Geometry2D" geometry NULL,
	"cellSpaceGeom_Geometry3D" geometry NULL,
	"cellSpaceName" varchar(100) NULL,
	"externalReference" "ExternalReferenceType" NULL,
	"level" varchar(100) NULL,
	"PoI" boolean NOT NULL,
	"CellSpaceID" varchar(100) NOT NULL,
	"PrimalSpaceLayerID" varchar(100) NOT NULL,
	"duality" varchar(100) NOT NULL,
	CONSTRAINT "chk_CellSpace_geom2d_surface" CHECK (
		"cellSpaceGeom_Geometry2D" IS NULL
		OR GeometryType("cellSpaceGeom_Geometry2D") IN ('POLYGON', 'MULTIPOLYGON')
	),
	CONSTRAINT "chk_CellSpace_geom3d_solid" CHECK (
		"cellSpaceGeom_Geometry3D" IS NULL
		OR (
			GeometryType("cellSpaceGeom_Geometry3D") IN ('POLYHEDRALSURFACE', 'TIN')
			AND ST_NDims("cellSpaceGeom_Geometry3D") = 3
			AND CG_IsSolid(CG_MakeSolid("cellSpaceGeom_Geometry3D"))
		)
	)
)
;

CREATE TABLE "DualSpaceLayer"
(
	"creationDate" timestamp without time zone NULL,
	"terminationDate" timestamp without time zone NULL,
	"isLogical" boolean NOT NULL,
	"isDirected" boolean NOT NULL,
	"DualSpaceLayerID" varchar(100) NOT NULL,
	"ThematicLayerID" varchar(100) NOT NULL
)
;

CREATE TABLE "Edge"
(
	"geometry" geometry NULL,
	"weight" real NOT NULL,
	"EdgeID" varchar(100) NOT NULL,
	"duality" varchar(100) NULL,
	"DualSpaceLayerID" varchar(100) NOT NULL,
	connects_node1 varchar(100) NOT NULL,
	connects_node2 varchar(100) NOT NULL,
	CONSTRAINT "chk_Edge_geometry_curve" CHECK (
		"geometry" IS NULL
		OR GeometryType("geometry") IN ('LINESTRING', 'MULTILINESTRING')
	)
)
;

CREATE TABLE "IndoorFeatures"
(
	"IndoorFeaturesID" varchar(100) NOT NULL,
	"layers" varchar(100) NULL  -- Reference to layers if needed, though usually layers point back to IndoorFeatures
)
;

CREATE TABLE "InterLayerConnection"
(
	"typeOfTopoExpression" "TopoExpressionValue" NOT NULL,
	"comment" text NULL,
	"InterLayerConnectionID" varchar(100) NOT NULL,
	"IndoorFeaturesID" varchar(100) NULL,
	"connectedLayers_1" varchar(100) NOT NULL,
	"connectedLayers_2" varchar(100) NOT NULL,
	"connectedNodes_1" varchar(100) NULL,
	"connectedNodes_2" varchar(100) NULL,
	"connectedCells_1" varchar(100) NULL,
	"connectedCells_2" varchar(100) NULL,
	CONSTRAINT "chk_InterLayerConnection_connectedNodes_pair" CHECK (
		("connectedNodes_1" IS NULL AND "connectedNodes_2" IS NULL)
		OR ("connectedNodes_1" IS NOT NULL AND "connectedNodes_2" IS NOT NULL)
	),
	CONSTRAINT "chk_InterLayerConnection_connectedCells_pair" CHECK (
		("connectedCells_1" IS NULL AND "connectedCells_2" IS NULL)
		OR ("connectedCells_1" IS NOT NULL AND "connectedCells_2" IS NOT NULL)
	)
)
;

CREATE TABLE "Node"
(
	"geometry" geometry NULL,
	"NodeID" varchar(100) NOT NULL,
	"duality" varchar(100) NOT NULL,
	"DualSpaceLayerID" varchar(100) NOT NULL,
	connects jsonb NULL,
	CONSTRAINT "chk_Node_geometry_point" CHECK (
		"geometry" IS NULL
		OR GeometryType("geometry") = 'POINT'
	)
)
;

CREATE TABLE "PrimalSpaceLayer"
(
	"creationDate" timestamp without time zone NULL,
	"terminationDate" timestamp without time zone NULL,
	"PrimalSpaceLayerID" varchar(100) NOT NULL,
	"ThematicLayerID" varchar(100) NOT NULL
)
;

CREATE TABLE "ThematicLayer"
(
	"semanticExtension" boolean NOT NULL,
	"theme" "ThemeLayerValue" NOT NULL,
	"ThematicLayerID" varchar(100) NOT NULL,
	"IndoorFeaturesID" varchar(100) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "CellBoundary" ADD CONSTRAINT "PK_CellBoundary"
	PRIMARY KEY ("CellBoundaryID")
;

ALTER TABLE "CellSpace" ADD CONSTRAINT "PK_CellSpace"
	PRIMARY KEY ("CellSpaceID")
;

ALTER TABLE "DualSpaceLayer" ADD CONSTRAINT "PK_DualSpaceLayer"
	PRIMARY KEY ("DualSpaceLayerID")
;

ALTER TABLE "Edge" ADD CONSTRAINT "PK_Edge"
	PRIMARY KEY ("EdgeID")
;

ALTER TABLE "IndoorFeatures" ADD CONSTRAINT "PK_IndoorFeatures"
	PRIMARY KEY ("IndoorFeaturesID")
;

ALTER TABLE "InterLayerConnection" ADD CONSTRAINT "PK_InterLayerConnection"
	PRIMARY KEY ("InterLayerConnectionID")
;

ALTER TABLE "Node" ADD CONSTRAINT "PK_Node"
	PRIMARY KEY ("NodeID")
;

ALTER TABLE "PrimalSpaceLayer" ADD CONSTRAINT "PK_PrimalSpaceLayer"
	PRIMARY KEY ("PrimalSpaceLayerID")
;

ALTER TABLE "ThematicLayer" ADD CONSTRAINT "PK_ThematicLayer"
	PRIMARY KEY ("ThematicLayerID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "CellBoundary" ADD CONSTRAINT "FK_CellBoundary_boundedBy"
	FOREIGN KEY ("boundedBy") REFERENCES "CellSpace" ("CellSpaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "CellBoundary" ADD CONSTRAINT "FK_CellBoundary_cellBoundaryMember"
	FOREIGN KEY ("PrimalSpaceLayerID") REFERENCES "PrimalSpaceLayer" ("PrimalSpaceLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "CellSpace" ADD CONSTRAINT "FK_CellSpace_cellSpaceMember"
	FOREIGN KEY ("PrimalSpaceLayerID") REFERENCES "PrimalSpaceLayer" ("PrimalSpaceLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "CellSpace" ADD CONSTRAINT "FK_CellSpace_duality"
	FOREIGN KEY ("duality") REFERENCES "Node" ("NodeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "DualSpaceLayer" ADD CONSTRAINT "FK_DualSpaceLayer_dualSpace"
	FOREIGN KEY ("ThematicLayerID") REFERENCES "ThematicLayer" ("ThematicLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Edge" ADD CONSTRAINT "FK_Edge_duality"
	FOREIGN KEY ("duality") REFERENCES "CellBoundary" ("CellBoundaryID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Edge" ADD CONSTRAINT "FK_Edge_DualSpaceLayer"
	FOREIGN KEY ("DualSpaceLayerID") REFERENCES "DualSpaceLayer" ("DualSpaceLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Edge" ADD CONSTRAINT "FK_Edge_connects_node1"
	FOREIGN KEY (connects_node1) REFERENCES "Node" ("NodeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Edge" ADD CONSTRAINT "FK_Edge_connects_node2"
	FOREIGN KEY (connects_node2) REFERENCES "Node" ("NodeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection" ADD CONSTRAINT "FK_InterLayerConnection_layerConnections"
	FOREIGN KEY ("IndoorFeaturesID") REFERENCES "IndoorFeatures" ("IndoorFeaturesID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection" ADD CONSTRAINT "FK_InterLayerConnection_connectedLayers_1"
	FOREIGN KEY ("connectedLayers_1") REFERENCES "ThematicLayer" ("ThematicLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection" ADD CONSTRAINT "FK_InterLayerConnection_connectedLayers_2"
	FOREIGN KEY ("connectedLayers_2") REFERENCES "ThematicLayer" ("ThematicLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection" ADD CONSTRAINT "FK_InterLayerConnection_connectedNodes_1"
	FOREIGN KEY ("connectedNodes_1") REFERENCES "Node" ("NodeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection" ADD CONSTRAINT "FK_InterLayerConnection_connectedNodes_2"
	FOREIGN KEY ("connectedNodes_2") REFERENCES "Node" ("NodeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection" ADD CONSTRAINT "FK_InterLayerConnection_connectedCells_1"
	FOREIGN KEY ("connectedCells_1") REFERENCES "CellSpace" ("CellSpaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection" ADD CONSTRAINT "FK_InterLayerConnection_connectedCells_2"
	FOREIGN KEY ("connectedCells_2") REFERENCES "CellSpace" ("CellSpaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Node" ADD CONSTRAINT "FK_Node_duality"
	FOREIGN KEY ("duality") REFERENCES "CellSpace" ("CellSpaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Node" ADD CONSTRAINT "FK_Node_DualSpaceLayer"
	FOREIGN KEY ("DualSpaceLayerID") REFERENCES "DualSpaceLayer" ("DualSpaceLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "PrimalSpaceLayer" ADD CONSTRAINT "FK_PrimalSpaceLayer_primalSpace"
	FOREIGN KEY ("ThematicLayerID") REFERENCES "ThematicLayer" ("ThematicLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "ThematicLayer" ADD CONSTRAINT "FK_ThematicLayer_layers"
	FOREIGN KEY ("IndoorFeaturesID") REFERENCES "IndoorFeatures" ("IndoorFeaturesID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "InterLayerConnection"
	IS 'Describes the connection between two thematic layers. '
;

COMMENT ON COLUMN "InterLayerConnection"."typeOfTopoExpression"
	IS 'Describes the topological relationship between two layers (e.g. overlaps, contains, etc.).'
;

COMMENT ON TABLE "ThematicLayer"
	IS 'A layer of specific theme aggregating a primal and/or a dual space of a given environment.'
;

COMMENT ON COLUMN "ThematicLayer"."semanticExtension"
	IS 'Indicates whether semantic information is associated (true) or not (false) to the primal space of the thematic layer.'
;

COMMENT ON COLUMN "ThematicLayer"."theme"
	IS 'Determines the theme of the layer (e.g topographic, logical, etc.).'
;
