/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 07-7月-2025 11:10:23 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

CREATE EXTENSION IF NOT EXISTS postgis
;
/* Drop Tables */

DROP TABLE IF EXISTS "Cellboundary" CASCADE
;

DROP TABLE IF EXISTS "Cellboundarygeometrytype" CASCADE
;

DROP TABLE IF EXISTS "Cellspace" CASCADE
;

DROP TABLE IF EXISTS "Cellspacegeometrytype" CASCADE
;

DROP TABLE IF EXISTS "Dualspacelayer" CASCADE
;

DROP TABLE IF EXISTS "Edge" CASCADE
;

DROP TABLE IF EXISTS "Externalobjectreferencetype" CASCADE
;

DROP TABLE IF EXISTS "Externalreferencetype" CASCADE
;

DROP TABLE IF EXISTS "Indoorfeatures" CASCADE
;

DROP TABLE IF EXISTS "Interlayerconnection" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection_CellSpace" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection_Node" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection_ThematicLayer" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection CellSpace" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection Node" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection ThematicLayer" CASCADE
;

DROP TABLE IF EXISTS "Node" CASCADE
;

DROP TABLE IF EXISTS "Primalspacelayer" CASCADE
;

DROP TABLE IF EXISTS "Thematiclayer" CASCADE
;

DROP TABLE IF EXISTS "Themelayervalue" CASCADE
;

DROP TABLE IF EXISTS "Topoexpressionvalue" CASCADE
;

/* Drop ENUM Types */

DROP TYPE IF EXISTS "TopoExpressionValue" CASCADE
;

DROP TYPE IF EXISTS "ThemeLayerValue" CASCADE
;

/* Create ENUM Types */

CREATE TYPE "ThemeLayerValue" AS ENUM (
	'Virtual',
	'Physical',
	'Tags',
	'Unknown'
)
;

CREATE TYPE "TopoExpressionValue" AS ENUM (
	'Contains',
	'Overlaps',
	'Equals',
	'Within',
	'Crosses',
	'Other'
)
;

/* Create Tables */

CREATE TABLE "Cellboundary"
(
	"Cellboundarygeom" geometry NULL,
	"Externalreference" varchar(100) NULL,
	"Isvirtual" boolean NULL,
	"CellboundaryID" varchar(100) NOT NULL,
	bounds varchar(100) NULL,
	"PrimalspacelayerID" varchar(100) NULL
)
;

CREATE TABLE "Cellboundarygeometrytype"
(
	"Geometry1d" geometry NULL,
	"Geometry2d" geometry NULL,
	"CellboundarygeometrytypeID" varchar(100) NOT NULL
)
;

CREATE TABLE "Cellspace"
(
	"Cellspacegeom" geometry NULL,
	"Cellspacename" varchar(100) NULL,
	"Externalreference" varchar(100) NULL,
	"Level" varchar(100) NULL,
	"Poi" boolean NULL,
	"CellspaceID" varchar(100) NOT NULL,
	"PrimalspacelayerID" varchar(100) NOT NULL,
	"duality" varchar(100) NULL
)
;

CREATE TABLE "Cellspacegeometrytype"
(
	"Geometry2d" geometry NULL,
	"Geometry3d" geometry NULL,
	"CellspacegeometrytypeID" varchar(100) NOT NULL
)
;

CREATE TABLE "Dualspacelayer"
(
	"Creationdate" timestamp without time zone NULL,
	"Terminationdate" timestamp without time zone NULL,
	"Islogical" boolean NULL,
	"Isdirected" boolean NULL,
	"DualspacelayerID" varchar(100) NOT NULL,
	"ThematiclayerID" varchar(100) NULL
)
;

CREATE TABLE "Edge"
(
	"Geometry" geometry NULL,
	"Weight" real NULL,
	"EdgeID" varchar(100) NOT NULL,
	"duality" varchar(100) NULL,
	"DualspacelayerID" varchar(100) NULL,
	connects jsonb NULL
)
;

CREATE TABLE "Externalobjectreferencetype"
(
	"Name" varchar(100) NULL,
	"Uri" varchar(100) NULL,
	"ExternalobjectreferencetypeID" varchar(100) NOT NULL
)
;

CREATE TABLE "Externalreferencetype"
(
	"Externalobject" varchar(100) NULL,
	"Informationsystem" varchar(100) NULL,
	"ExternalreferencetypeID" varchar(100) NOT NULL
)
;

CREATE TABLE "Indoorfeatures"
(
	"IndoorfeaturesID" varchar(100) NOT NULL,
	"layers" varchar(100) NULL  -- Reference to layers if needed, though usually layers point back to IndoorFeatures
)
;

CREATE TABLE "Interlayerconnection"
(
	"Typeoftopoexpression" "TopoExpressionValue" NULL,
	"Comment" text NULL,
	"InterlayerconnectionID" varchar(100) NOT NULL,
	"IndoorfeaturesID" varchar(100) NULL
)
;

CREATE TABLE "InterLayerConnection_CellSpace"
(
	"connectedCells" varchar(100) NULL,
	"InterlayerconnectionID" varchar(100) NULL
)
;

CREATE TABLE "InterLayerConnection_Node"
(
	"connectedNodes" varchar(100) NULL,
	"InterlayerconnectionID" varchar(100) NULL
)
;

CREATE TABLE "InterLayerConnection_ThematicLayer"
(
	"connectedLayers" varchar(100) NULL,
	"InterlayerconnectionID" varchar(100) NULL
)
;

CREATE TABLE "Node"
(
	"Geometry" geometry NULL,
	"NodeID" varchar(100) NOT NULL,
	"duality" varchar(100) NULL,
	"DualspacelayerID" varchar(100) NOT NULL,
	connects jsonb NULL
)
;

CREATE TABLE "Primalspacelayer"
(
	"Creationdate" timestamp without time zone NULL,
	"Terminationdate" timestamp without time zone NULL,
	"PrimalspacelayerID" varchar(100) NOT NULL,
	"ThematiclayerID" varchar(100) NULL
)
;

CREATE TABLE "Thematiclayer"
(
	"Semanticextension" boolean NULL,
	"Theme" "ThemeLayerValue" NULL,
	"ThematiclayerID" varchar(100) NOT NULL,
	"IndoorfeaturesID" varchar(100) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Cellboundary" ADD CONSTRAINT "PK_Cellboundary"
	PRIMARY KEY ("CellboundaryID")
;

ALTER TABLE "Cellboundarygeometrytype" ADD CONSTRAINT "PK_Cellboundarygeometrytype"
	PRIMARY KEY ("CellboundarygeometrytypeID")
;

ALTER TABLE "Cellspace" ADD CONSTRAINT "PK_Cellspace"
	PRIMARY KEY ("CellspaceID")
;

ALTER TABLE "Cellspacegeometrytype" ADD CONSTRAINT "PK_Cellspacegeometrytype"
	PRIMARY KEY ("CellspacegeometrytypeID")
;

ALTER TABLE "Dualspacelayer" ADD CONSTRAINT "PK_Dualspacelayer"
	PRIMARY KEY ("DualspacelayerID")
;

ALTER TABLE "Edge" ADD CONSTRAINT "PK_Edge"
	PRIMARY KEY ("EdgeID")
;

ALTER TABLE "Externalobjectreferencetype" ADD CONSTRAINT "PK_Externalobjectreferencetype"
	PRIMARY KEY ("ExternalobjectreferencetypeID")
;

ALTER TABLE "Externalreferencetype" ADD CONSTRAINT "PK_Externalreferencetype"
	PRIMARY KEY ("ExternalreferencetypeID")
;

ALTER TABLE "Indoorfeatures" ADD CONSTRAINT "PK_Indoorfeatures"
	PRIMARY KEY ("IndoorfeaturesID")
;

ALTER TABLE "Interlayerconnection" ADD CONSTRAINT "PK_Interlayerconnection"
	PRIMARY KEY ("InterlayerconnectionID")
;

ALTER TABLE "Node" ADD CONSTRAINT "PK_Node"
	PRIMARY KEY ("NodeID")
;

ALTER TABLE "Primalspacelayer" ADD CONSTRAINT "PK_Primalspacelayer"
	PRIMARY KEY ("PrimalspacelayerID")
;

ALTER TABLE "Thematiclayer" ADD CONSTRAINT "PK_Thematiclayer"
	PRIMARY KEY ("ThematiclayerID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Cellboundary" ADD CONSTRAINT "FK_CellBoundary_boundedBy"
	FOREIGN KEY (bounds) REFERENCES "Cellspace" ("CellspaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Cellboundary" ADD CONSTRAINT "FK_CellBoundary_cellBoundaryMember"
	FOREIGN KEY ("PrimalspacelayerID") REFERENCES "Primalspacelayer" ("PrimalspacelayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Cellspace" ADD CONSTRAINT "FK_CellSpace_cellSpaceMember"
	FOREIGN KEY ("PrimalspacelayerID") REFERENCES "Primalspacelayer" ("PrimalspacelayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Cellspace" ADD CONSTRAINT "FK_Cellspace_duality"
	FOREIGN KEY ("duality") REFERENCES "Node" ("NodeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Dualspacelayer" ADD CONSTRAINT "FK_DualSpaceLayer_dualSpace"
	FOREIGN KEY ("ThematiclayerID") REFERENCES "Thematiclayer" ("ThematiclayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Edge" ADD CONSTRAINT "FK_Edge_duality"
	FOREIGN KEY ("duality") REFERENCES "Cellboundary" ("CellboundaryID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Edge" ADD CONSTRAINT "FK_Edge_Dualspacelayer"
	FOREIGN KEY ("DualspacelayerID") REFERENCES "Dualspacelayer" ("DualspacelayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Interlayerconnection" ADD CONSTRAINT "FK_InterLayerConnection_layerConnections"
	FOREIGN KEY ("IndoorfeaturesID") REFERENCES "Indoorfeatures" ("IndoorfeaturesID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection_CellSpace" ADD CONSTRAINT "FK_InterLayerConnection_CellSpace_connectedCells"
	FOREIGN KEY ("connectedCells") REFERENCES "Cellspace" ("CellspaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection_CellSpace" ADD CONSTRAINT "FK_InterLayerConnection_CellSpace_InterLayerConnection"
	FOREIGN KEY ("InterlayerconnectionID") REFERENCES "Interlayerconnection" ("InterlayerconnectionID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection_Node" ADD CONSTRAINT "FK_InterLayerConnection_Node_connectedNodes"
	FOREIGN KEY ("connectedNodes") REFERENCES "Node" ("NodeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection_Node" ADD CONSTRAINT "FK_InterLayerConnection_Node_InterLayerConnection"
	FOREIGN KEY ("InterlayerconnectionID") REFERENCES "Interlayerconnection" ("InterlayerconnectionID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection_ThematicLayer" ADD CONSTRAINT "FK_InterLayerConnection_ThematicLayer_connectedLayers"
	FOREIGN KEY ("connectedLayers") REFERENCES "Thematiclayer" ("ThematiclayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection_ThematicLayer" ADD CONSTRAINT "FK_InterLayerConnection_ThematicLayer_InterLayerConnection"
	FOREIGN KEY ("InterlayerconnectionID") REFERENCES "Interlayerconnection" ("InterlayerconnectionID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Node" ADD CONSTRAINT "FK_Node_duality"
	FOREIGN KEY ("duality") REFERENCES "Cellspace" ("CellspaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Node" ADD CONSTRAINT "FK_Node_Dualspacelayer"
	FOREIGN KEY ("DualspacelayerID") REFERENCES "Dualspacelayer" ("DualspacelayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Primalspacelayer" ADD CONSTRAINT "FK_PrimalSpaceLayer_primalSpace"
	FOREIGN KEY ("ThematiclayerID") REFERENCES "Thematiclayer" ("ThematiclayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Thematiclayer" ADD CONSTRAINT "FK_ThematicLayer_layers"
	FOREIGN KEY ("IndoorfeaturesID") REFERENCES "Indoorfeatures" ("IndoorfeaturesID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Interlayerconnection"
	IS 'Describes the connection between two thematic layers. '
;

COMMENT ON COLUMN "Interlayerconnection"."Typeoftopoexpression"
	IS 'Describes the topological relationship between two layers (e.g. overlaps, contains, etc.).'
;

COMMENT ON TABLE "Thematiclayer"
	IS 'A layer of specific theme aggregating a primal and/or a dual space of a given environment.'
;

COMMENT ON COLUMN "Thematiclayer"."Semanticextension"
	IS 'Indicates whether semantic information is associated (true) or not (false) to the primal space of the thematic layer.'
;

COMMENT ON COLUMN "Thematiclayer"."Theme"
	IS 'Determines the theme of the layer (e.g topographic, logical, etc.).'
;
