/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 07-7月-2025 11:10:23 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

CREATE EXTENSION IF NOT EXISTS postgis
;
/* Drop Tables */

DROP TABLE IF EXISTS "CellBoundary" CASCADE
;

DROP TABLE IF EXISTS "CellBoundaryGeometryType" CASCADE
;

DROP TABLE IF EXISTS "CellSpace" CASCADE
;

DROP TABLE IF EXISTS "CellSpaceGeometryType" CASCADE
;

DROP TABLE IF EXISTS "DualSpaceLayer" CASCADE
;

DROP TABLE IF EXISTS "Edge" CASCADE
;

DROP TABLE IF EXISTS "ExternalObjectReferenceType" CASCADE
;

DROP TABLE IF EXISTS "ExternalReferenceType" CASCADE
;

DROP TABLE IF EXISTS "IndoorFeatures" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection_CellSpace" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection_Node" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection_ThematicLayer" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection CellSpace" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection Node" CASCADE
;

DROP TABLE IF EXISTS "InterLayerConnection ThematicLayer" CASCADE
;

DROP TABLE IF EXISTS "Node" CASCADE
;

DROP TABLE IF EXISTS "PrimalSpaceLayer" CASCADE
;

DROP TABLE IF EXISTS "ThematicLayer" CASCADE
;

DROP TABLE IF EXISTS "ThemeLayerValue" CASCADE
;

DROP TABLE IF EXISTS "TopoExpressionValue" CASCADE
;

/* Drop ENUM and composite Types */

DROP TYPE IF EXISTS "TopoExpressionValue" CASCADE
;

DROP TYPE IF EXISTS "ThemeLayerValue" CASCADE
;

DROP TYPE IF EXISTS "ExternalReferenceType" CASCADE
;

DROP TYPE IF EXISTS "ExternalObjectReferenceType" CASCADE
;

/* Create ENUM Types */

CREATE TYPE "ThemeLayerValue" AS ENUM (
	'Virtual',
	'Physical',
	'Tags',
	'Unknown'
)
;

CREATE TYPE "TopoExpressionValue" AS ENUM (
	'Contains',
	'Overlaps',
	'Equals',
	'Within',
	'Crosses',
	'Other'
)
;

/* Create composite Types (UML DataTypes for external references) */

CREATE TYPE "ExternalObjectReferenceType" AS (
	"Name" varchar(100),
	"Uri" text
)
;

CREATE TYPE "ExternalReferenceType" AS (
	"ExternalObject" "ExternalObjectReferenceType",
	"InformationSystem" text
)
;

/* Create Tables */

CREATE TABLE "CellBoundary"
(
	"cellBoundaryGeom_geometry1D" geometry NULL,
	"cellBoundaryGeom_geometry2D" geometry NULL,
	"externalReference" "ExternalReferenceType" NULL,
	"Isvirtual" boolean NULL,
	"CellBoundaryID" varchar(100) NOT NULL,
	bounds varchar(100) NULL,
	"PrimalSpaceLayerID" varchar(100) NULL,
	CONSTRAINT "chk_CellBoundary_geom_xor" CHECK (
		NOT ("cellBoundaryGeom_geometry1D" IS NOT NULL AND "cellBoundaryGeom_geometry2D" IS NOT NULL)
	)
)
;

CREATE TABLE "CellSpace"
(
	"cellSpaceGeom_geometry2D" geometry NULL,
	"cellSpaceGeom_geometry3D" geometry NULL,
	"CellSpaceName" varchar(100) NULL,
	"externalReference" "ExternalReferenceType" NULL,
	"Level" varchar(100) NULL,
	"Poi" boolean NULL,
	"CellSpaceID" varchar(100) NOT NULL,
	"PrimalSpaceLayerID" varchar(100) NOT NULL,
	"duality" varchar(100) NULL,
	CONSTRAINT "chk_CellSpace_geom_xor" CHECK (
		NOT ("cellSpaceGeom_geometry2D" IS NOT NULL AND "cellSpaceGeom_geometry3D" IS NOT NULL)
	)
)
;

CREATE TABLE "DualSpaceLayer"
(
	"Creationdate" timestamp without time zone NULL,
	"Terminationdate" timestamp without time zone NULL,
	"Islogical" boolean NULL,
	"Isdirected" boolean NULL,
	"DualSpaceLayerID" varchar(100) NOT NULL,
	"ThematicLayerID" varchar(100) NULL
)
;

CREATE TABLE "Edge"
(
	"Geometry" geometry NULL,
	"Weight" real NULL,
	"EdgeID" varchar(100) NOT NULL,
	"duality" varchar(100) NULL,
	"DualSpaceLayerID" varchar(100) NULL,
	connects jsonb NULL
)
;

CREATE TABLE "IndoorFeatures"
(
	"IndoorFeaturesID" varchar(100) NOT NULL,
	"layers" varchar(100) NULL  -- Reference to layers if needed, though usually layers point back to IndoorFeatures
)
;

CREATE TABLE "InterLayerConnection"
(
	"Typeoftopoexpression" "TopoExpressionValue" NULL,
	"Comment" text NULL,
	"InterLayerConnectionID" varchar(100) NOT NULL,
	"IndoorFeaturesID" varchar(100) NULL
)
;

CREATE TABLE "InterLayerConnection_CellSpace"
(
	"connectedCells" varchar(100) NULL,
	"InterLayerConnectionID" varchar(100) NULL
)
;

CREATE TABLE "InterLayerConnection_Node"
(
	"connectedNodes" varchar(100) NULL,
	"InterLayerConnectionID" varchar(100) NULL
)
;

CREATE TABLE "InterLayerConnection_ThematicLayer"
(
	"connectedLayers" varchar(100) NULL,
	"InterLayerConnectionID" varchar(100) NULL
)
;

CREATE TABLE "Node"
(
	"Geometry" geometry NULL,
	"NodeID" varchar(100) NOT NULL,
	"duality" varchar(100) NULL,
	"DualSpaceLayerID" varchar(100) NOT NULL,
	connects jsonb NULL
)
;

CREATE TABLE "PrimalSpaceLayer"
(
	"Creationdate" timestamp without time zone NULL,
	"Terminationdate" timestamp without time zone NULL,
	"PrimalSpaceLayerID" varchar(100) NOT NULL,
	"ThematicLayerID" varchar(100) NULL
)
;

CREATE TABLE "ThematicLayer"
(
	"Semanticextension" boolean NULL,
	"Theme" "ThemeLayerValue" NULL,
	"ThematicLayerID" varchar(100) NOT NULL,
	"IndoorFeaturesID" varchar(100) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "CellBoundary" ADD CONSTRAINT "PK_CellBoundary"
	PRIMARY KEY ("CellBoundaryID")
;

ALTER TABLE "CellSpace" ADD CONSTRAINT "PK_CellSpace"
	PRIMARY KEY ("CellSpaceID")
;

ALTER TABLE "DualSpaceLayer" ADD CONSTRAINT "PK_DualSpaceLayer"
	PRIMARY KEY ("DualSpaceLayerID")
;

ALTER TABLE "Edge" ADD CONSTRAINT "PK_Edge"
	PRIMARY KEY ("EdgeID")
;

ALTER TABLE "IndoorFeatures" ADD CONSTRAINT "PK_IndoorFeatures"
	PRIMARY KEY ("IndoorFeaturesID")
;

ALTER TABLE "InterLayerConnection" ADD CONSTRAINT "PK_InterLayerConnection"
	PRIMARY KEY ("InterLayerConnectionID")
;

ALTER TABLE "Node" ADD CONSTRAINT "PK_Node"
	PRIMARY KEY ("NodeID")
;

ALTER TABLE "PrimalSpaceLayer" ADD CONSTRAINT "PK_PrimalSpaceLayer"
	PRIMARY KEY ("PrimalSpaceLayerID")
;

ALTER TABLE "ThematicLayer" ADD CONSTRAINT "PK_ThematicLayer"
	PRIMARY KEY ("ThematicLayerID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "CellBoundary" ADD CONSTRAINT "FK_CellBoundary_boundedBy"
	FOREIGN KEY (bounds) REFERENCES "CellSpace" ("CellSpaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "CellBoundary" ADD CONSTRAINT "FK_CellBoundary_cellBoundaryMember"
	FOREIGN KEY ("PrimalSpaceLayerID") REFERENCES "PrimalSpaceLayer" ("PrimalSpaceLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "CellSpace" ADD CONSTRAINT "FK_CellSpace_cellSpaceMember"
	FOREIGN KEY ("PrimalSpaceLayerID") REFERENCES "PrimalSpaceLayer" ("PrimalSpaceLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "CellSpace" ADD CONSTRAINT "FK_CellSpace_duality"
	FOREIGN KEY ("duality") REFERENCES "Node" ("NodeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "DualSpaceLayer" ADD CONSTRAINT "FK_DualSpaceLayer_dualSpace"
	FOREIGN KEY ("ThematicLayerID") REFERENCES "ThematicLayer" ("ThematicLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Edge" ADD CONSTRAINT "FK_Edge_duality"
	FOREIGN KEY ("duality") REFERENCES "CellBoundary" ("CellBoundaryID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Edge" ADD CONSTRAINT "FK_Edge_DualSpaceLayer"
	FOREIGN KEY ("DualSpaceLayerID") REFERENCES "DualSpaceLayer" ("DualSpaceLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection" ADD CONSTRAINT "FK_InterLayerConnection_layerConnections"
	FOREIGN KEY ("IndoorFeaturesID") REFERENCES "IndoorFeatures" ("IndoorFeaturesID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection_CellSpace" ADD CONSTRAINT "FK_InterLayerConnection_CellSpace_connectedCells"
	FOREIGN KEY ("connectedCells") REFERENCES "CellSpace" ("CellSpaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection_CellSpace" ADD CONSTRAINT "FK_InterLayerConnection_CellSpace_InterLayerConnection"
	FOREIGN KEY ("InterLayerConnectionID") REFERENCES "InterLayerConnection" ("InterLayerConnectionID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection_Node" ADD CONSTRAINT "FK_InterLayerConnection_Node_connectedNodes"
	FOREIGN KEY ("connectedNodes") REFERENCES "Node" ("NodeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection_Node" ADD CONSTRAINT "FK_InterLayerConnection_Node_InterLayerConnection"
	FOREIGN KEY ("InterLayerConnectionID") REFERENCES "InterLayerConnection" ("InterLayerConnectionID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection_ThematicLayer" ADD CONSTRAINT "FK_InterLayerConnection_ThematicLayer_connectedLayers"
	FOREIGN KEY ("connectedLayers") REFERENCES "ThematicLayer" ("ThematicLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "InterLayerConnection_ThematicLayer" ADD CONSTRAINT "FK_InterLayerConnection_ThematicLayer_InterLayerConnection"
	FOREIGN KEY ("InterLayerConnectionID") REFERENCES "InterLayerConnection" ("InterLayerConnectionID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Node" ADD CONSTRAINT "FK_Node_duality"
	FOREIGN KEY ("duality") REFERENCES "CellSpace" ("CellSpaceID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Node" ADD CONSTRAINT "FK_Node_DualSpaceLayer"
	FOREIGN KEY ("DualSpaceLayerID") REFERENCES "DualSpaceLayer" ("DualSpaceLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "PrimalSpaceLayer" ADD CONSTRAINT "FK_PrimalSpaceLayer_primalSpace"
	FOREIGN KEY ("ThematicLayerID") REFERENCES "ThematicLayer" ("ThematicLayerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "ThematicLayer" ADD CONSTRAINT "FK_ThematicLayer_layers"
	FOREIGN KEY ("IndoorFeaturesID") REFERENCES "IndoorFeatures" ("IndoorFeaturesID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "InterLayerConnection"
	IS 'Describes the connection between two thematic layers. '
;

COMMENT ON COLUMN "InterLayerConnection"."Typeoftopoexpression"
	IS 'Describes the topological relationship between two layers (e.g. overlaps, contains, etc.).'
;

COMMENT ON TABLE "ThematicLayer"
	IS 'A layer of specific theme aggregating a primal and/or a dual space of a given environment.'
;

COMMENT ON COLUMN "ThematicLayer"."Semanticextension"
	IS 'Indicates whether semantic information is associated (true) or not (false) to the primal space of the thematic layer.'
;

COMMENT ON COLUMN "ThematicLayer"."Theme"
	IS 'Determines the theme of the layer (e.g topographic, logical, etc.).'
;
