name: generate_IndoorGML2_Part2
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: metanorma/metanorma:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout IndoorGML source repository
        uses: actions/checkout@v4
        with:
          repository: opengeospatial/IndoorGML-SWG
          path: IndoorGML2_Part2

      - name: Generate XML document
        working-directory: IndoorGML2_Part2/IndoorGML2/IndoorGML2_metanorma
        run: |
          cd "Part II/XML"
          metanorma compile --agree-to-terms -t ogc -x html,pdf standard_implementation/document.adoc
          cp standard_implementation/document.html "$GITHUB_WORKSPACE/main/26-042.html"
          cp standard_implementation/document.pdf "$GITHUB_WORKSPACE/main/26-042.pdf"

      - name: Generate JSON document
        working-directory: IndoorGML2_Part2/IndoorGML2/IndoorGML2_metanorma
        run: |
          cd "Part II/JSON/standard_implementation/"
          metanorma compile --agree-to-terms -t ogc -x html,pdf document.adoc
          cp document.html "$GITHUB_WORKSPACE/main/26-043.html"
          cp document.pdf "$GITHUB_WORKSPACE/main/26-043.pdf"

      - name: Generate SQL document
        working-directory: IndoorGML2_Part2/IndoorGML2/IndoorGML2_metanorma
        run: |
          cd "Part II/SQL"
          metanorma compile --agree-to-terms -t ogc -x html,pdf standard_implementation/document.adoc
          cp standard_implementation/document.html "$GITHUB_WORKSPACE/main/26-044.html"
          cp standard_implementation/document.pdf "$GITHUB_WORKSPACE/main/26-044.pdf"

      - name: Commit and push generated documents
        working-directory: main
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE/main"
          git config user.name "opengeospatial"
          git config user.email "opengeospatial@users.noreply.github.com"

          git add -- \
            26-042.html 26-042.pdf \
            26-043.html 26-043.pdf \
            26-044.html 26-044.pdf
          
          git commit -m "Automated generation of HTML and PDF documents"
          git push 
